### ISSUE TITLE
[Auth - Forgot Password] HTTP code still response 200 when error

### ISSUE THREAD

**Issue by kztera** [tridevi-team/renthub-backend#27]
![IMG_20240929_112349_077.jpg](https://github.com/user-attachments/assets/9d093b1a-2577-4a33-a55a-40033a4464c5)

Expected: Error code

**Comment by tmquang0209** [comment]
I don't like. I want to expect http status code is 404? Are u ok?

**Comment by kztera** [comment]
@tmquang0209 Any code is fine as long as it's not 200
